name: fconnectivity
description: Connectivity package that contains useful utilities for checking if device is connected to the internet.
version: 0.3.0
homepage: https://github.com/Haidar0096/fconnectivity

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  internet_connection_checker_plus: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

# The following section is specific to Flutter packages.
flutter: